# Título

## subtitulo 

### subsubtitulo 

#### subsubtitulo 

El área bajo la curva es la integral $$ \int_{0}^{\pi} \sin(x) \, dx  = 0 $$

$$ \nabla \cdot \vec{B} = 0$$

$$ \dfrac{\partial f}{ \partial x} = $$




* *Italicas*
* **Negritas**
* ***NegritaeItalicas***

<img src = "Images/ENIAC.jpg"  width="500" height="300"/>

In [ ]:
"Hello world!";

In [ ]:
print("Hellos wordl!")

# Más sobres la estructuras de datos 

Recordemos que podemos las listas como:

```python
lista = [1, 3, 5]
```

In [ ]:
lista = [4, 6, 66, 18, 110, 1, 14000]

In [ ]:
lista[3] = 7

In [ ]:
lista

## Métodos de las listas

```python
lista.append(x)
```

In [ ]:
lista.append(16)

In [ ]:
lista

Object `append ` not found.


```python
lista.insert(i, x)```

In [ ]:
lista.insert(1, 2)

In [ ]:
lista

In [ ]:
lista.remove(4)

In [ ]:
lista

In [ ]:
lista.pop(3)

In [ ]:
lista

In [ ]:
lista.sort()

In [ ]:
lista

In [ ]:
lista.reverse()

In [ ]:
lista

In [ ]:
l2 = lista.copy()

In [ ]:
l2

In [ ]:
len(lista)

In [ ]:
lista.clear()

In [ ]:
lista

# Paquetes de Python 

In [ ]:
import matrices as matr

In [ ]:
matr.dimension([[1, 3], [3, 5]])

In [ ]:
from numpy import *

In [1]:
from numpy import pi

In [3]:
sin(pi)

NameError: name 'sin' is not defined

In [4]:
import numpy as np

In [2]:
from numpy import *

In [3]:
pi

3.141592653589793

In [4]:
sin(pi/2)

1.0

In [5]:
a = linspace(0, 2*pi, 100)

In [10]:
a

array([0.        , 0.06346652, 0.12693304, 0.19039955, 0.25386607,
       0.31733259, 0.38079911, 0.44426563, 0.50773215, 0.57119866,
       0.63466518, 0.6981317 , 0.76159822, 0.82506474, 0.88853126,
       0.95199777, 1.01546429, 1.07893081, 1.14239733, 1.20586385,
       1.26933037, 1.33279688, 1.3962634 , 1.45972992, 1.52319644,
       1.58666296, 1.65012947, 1.71359599, 1.77706251, 1.84052903,
       1.90399555, 1.96746207, 2.03092858, 2.0943951 , 2.15786162,
       2.22132814, 2.28479466, 2.34826118, 2.41172769, 2.47519421,
       2.53866073, 2.60212725, 2.66559377, 2.72906028, 2.7925268 ,
       2.85599332, 2.91945984, 2.98292636, 3.04639288, 3.10985939,
       3.17332591, 3.23679243, 3.30025895, 3.36372547, 3.42719199,
       3.4906585 , 3.55412502, 3.61759154, 3.68105806, 3.74452458,
       3.8079911 , 3.87145761, 3.93492413, 3.99839065, 4.06185717,
       4.12532369, 4.1887902 , 4.25225672, 4.31572324, 4.37918976,
       4.44265628, 4.5061228 , 4.56958931, 4.63305583, 4.69652

In [11]:
a[6:]

array([0.38079911, 0.44426563, 0.50773215, 0.57119866, 0.63466518,
       0.6981317 , 0.76159822, 0.82506474, 0.88853126, 0.95199777,
       1.01546429, 1.07893081, 1.14239733, 1.20586385, 1.26933037,
       1.33279688, 1.3962634 , 1.45972992, 1.52319644, 1.58666296,
       1.65012947, 1.71359599, 1.77706251, 1.84052903, 1.90399555,
       1.96746207, 2.03092858, 2.0943951 , 2.15786162, 2.22132814,
       2.28479466, 2.34826118, 2.41172769, 2.47519421, 2.53866073,
       2.60212725, 2.66559377, 2.72906028, 2.7925268 , 2.85599332,
       2.91945984, 2.98292636, 3.04639288, 3.10985939, 3.17332591,
       3.23679243, 3.30025895, 3.36372547, 3.42719199, 3.4906585 ,
       3.55412502, 3.61759154, 3.68105806, 3.74452458, 3.8079911 ,
       3.87145761, 3.93492413, 3.99839065, 4.06185717, 4.12532369,
       4.1887902 , 4.25225672, 4.31572324, 4.37918976, 4.44265628,
       4.5061228 , 4.56958931, 4.63305583, 4.69652235, 4.75998887,
       4.82345539, 4.88692191, 4.95038842, 5.01385494, 5.07732

In [19]:
b = arange(0, 2*pi, 0.01)

In [22]:
ceros = zeros(100)

In [25]:
unos = ones(100)

In [31]:
unos

array([1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1.,
       1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1.,
       1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1.,
       1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1.,
       1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1.,
       1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1.])

In [27]:
type(unos)

numpy.ndarray

In [24]:
type(ceros)

numpy.ndarray

In [20]:
type(a)

numpy.ndarray

In [21]:
type(b)

numpy.ndarray

In [29]:
v1 = array([1.9, 3.2, 4.0])

In [32]:
v2 = array([2, 3, 4.0])

In [33]:
v1 + v2

array([3.9, 6.2, 8. ])

In [34]:
M = array([[1 ,2], [3, 4]])

In [36]:
I = array([[1 ,0], [0, 1]])

In [43]:
M*I

array([[1, 0],
       [0, 4]])

In [44]:
dot(M, I)

array([[1, 2],
       [3, 4]])

In [46]:
cross([1, 0, 0] , [0, 1, 0])

array([0, 0, 1])

In [53]:
M

array([[1, 2],
       [3, 4]])

### reshape 

In [18]:
x = arange(27)

In [19]:
type(x)

numpy.ndarray

In [20]:
y = arange(27).reshape(3, 3, 3)

In [21]:
y

array([[[ 0,  1,  2],
        [ 3,  4,  5],
        [ 6,  7,  8]],

       [[ 9, 10, 11],
        [12, 13, 14],
        [15, 16, 17]],

       [[18, 19, 20],
        [21, 22, 23],
        [24, 25, 26]]])

In [26]:
x[: 3]

array([0, 1, 2])

In [32]:
y

array([[[ 0,  1,  2],
        [ 3,  4,  5],
        [ 6,  7,  8]],

       [[ 9, 10, 11],
        [12, 13, 14],
        [15, 16, 17]],

       [[18, 19, 20],
        [21, 22, 23],
        [24, 25, 26]]])

In [34]:
y[1][0][0]

9