# Utilizando los simbolos del gato "#" 


## antes de tu texto pordemos crear especies de 


### titulos y subtitulos, estos van de mas a grande a mas pequeño


#### Por ejemplo:  "# Esto es un titulo"

# Presionando "Esc" + "m" podemos pasar de un tipo de celda a una celda de tipo "Markdown"

In [5]:
Y presionando "Esc" + "a" podemos pasar de un tipo de celda a una celda de tipo "Code"

SyntaxError: invalid syntax (<ipython-input-5-11a8f2192c27>, line 1)

# Para ejecutar la celda que estamos seleccionando tenemos que apretar las siguientes teclas: "Shift" + "Enter"

Como podemos observar, en la celda anterior podemos ver que esta es de tipo $Markdown$ y $Latex$, lo que significa que en este notebook y en las celdas de tipo $Markdown$ podemos tambien podemos introducir codigo $Latex.$ 

Como por ejemplo:

El área bajo la curva es la integral $$ \int_{0}^{\pi} \sin(x) \, dx = 0 $$

$$ \nabla \cdot \vec{B} = 0$$

$$ \dfrac{\partial f}{\partial x} = 7x$$

Tenemos varios tipos de letras entre ellas estan:

* *Italicas* 
* **Negritas**
* ***Negritas e Italicas***


Tambien podemos meter imagenes en nuestro notebook, con "img src = *Nombre de archivo* **,** ***Ruta de la imagen*** **o** ***URL de la imagen***"

<img src = "arboles.jpg" > 

Asignación en Python, donde a la variable ***a*** le asignas un string, en este caso **Hello world!!!** 

In [8]:
a = 'Hello world!!!'

En esta linea imprimimos la variable **a**

In [9]:
print(a)

Hello world!!!


Recuerda que con las teclas *shift* + *Enter* ejecutas la línea sobre la que estas. 

## Listas (Estructura de Datos)

#### Declaración de una lista en Python:

```python
nombreDeTuLista = [1, 3, 5]
```

In [1]:
lista = [0,2,4,6,8]

In [2]:
lista[3]

6

In [3]:
lista

[0, 2, 4, 6, 8]

## Métodos de las listas:

```python
lista.append(x)
```

El método *append(x)* agrega el elemento *x* al final de nuestra lista.

In [4]:
lista

[0, 2, 4, 6, 8]

In [5]:
lista.append(1000)

In [6]:
lista


[0, 2, 4, 6, 8, 1000]

```python
lista.insert(i, x)```

El método *insert(i, x)* agrega el elemento *x* en el indice *i* de nuestra lista.

In [9]:
lista

[0, 2, 4, 6, 8, 1000]

In [11]:
lista.insert(0, 'esto')

In [12]:
lista

['esto', 0, 2, 4, 6, 8, 1000]

```python
lista.remove(x)```

El método *remove(x)* elimina el elemento *x* de nuestra lista, si el elemento *x* no esta en nuestra lista, este manda un error.

In [14]:
lista

['esto', 0, 2, 4, 6, 8, 1000]

In [15]:
lista.remove(0)

In [16]:
lista

['esto', 2, 4, 6, 8, 1000]

In [17]:
lista.remove(123)

ValueError: list.remove(x): x not in list

In [18]:
lista

['esto', 2, 4, 6, 8, 1000]

In [19]:
lista.remove(1000)

In [20]:
lista

['esto', 2, 4, 6, 8]

```python
lista.pop(x)```

El método *pop(i)* devuelve el elemento que esta en el indice *i*, debemos de meter un índice *i* valido, no debemos salirnos de nuestro rango.

In [24]:
lista

[2, 6, 8]

In [21]:
lista.pop(2)

4

In [23]:
lista.pop(0)

'esto'

```python
lista.sort()```

El método *sort* ordena nuestra lista de menor a mayor, este solo funciona con números.

In [45]:
lista2 = [3,4,5,1,2,3,2.5]

In [46]:
lista2

[3, 4, 5, 1, 2, 3, 2.5]

In [47]:
lista2.sort()

In [48]:
lista2

[1, 2, 2.5, 3, 3, 4, 5]

```python
lista.reverse()```

In [52]:
lista2.reverse()

In [53]:
lista2

[5, 4, 3, 3, 2.5, 2, 1]

```python
lista.copy()```

El método *copy()* genera una cogia de la lista con la que lo mandamos a llamar.

In [56]:
lista3 = lista2.copy()

In [57]:
lista3

[5, 4, 3, 3, 2.5, 2, 1]

```python
len(listaX)```

El método *len()* nos devuelve la longitud de nuestra cadena.

In [58]:
len(lista3)

7

```python
lista.clear()```

El método *clear()* nos vacía nuestra lista.

In [62]:
lista3.clear()

In [63]:
lista3

[]

## ¿Paqueterías de Python?

In [6]:
from numpy import *

In [7]:
from numpy import pi

In [8]:
pi

3.141592653589793

In [9]:
sin(pi)

1.2246467991473532e-16

In [10]:
import numpy as np

In [11]:
from numpy import *

In [12]:
pi

3.141592653589793

In [13]:
np.pi

3.141592653589793

In [14]:
sin(pi/2)

1.0

## ¿Arrays? 

In [15]:
A = linspace(0, 5, 10)

In [16]:
A

array([0.        , 0.55555556, 1.11111111, 1.66666667, 2.22222222,
       2.77777778, 3.33333333, 3.88888889, 4.44444444, 5.        ])

In [17]:
a

NameError: name 'a' is not defined

In [18]:
a[5:7]

NameError: name 'a' is not defined

In [19]:
b = arange(0, 1, 0.1)

In [20]:
b

array([0. , 0.1, 0.2, 0.3, 0.4, 0.5, 0.6, 0.7, 0.8, 0.9])

In [21]:
B = arange(0, 2, 1)

In [22]:
B

array([0, 1])

In [23]:
Unos = ones(10)

In [24]:
Unos

array([1., 1., 1., 1., 1., 1., 1., 1., 1., 1.])

In [25]:
type(Unos)

numpy.ndarray

In [26]:
type(B)

numpy.ndarray

Asignación en Python de un arreglo.

In [27]:
v1 = array([1, 2.5, 9, 9])

Imprimimos la variable (el arreglo)

In [28]:
v1

array([1. , 2.5, 9. , 9. ])

Asignamos 10000, en el indice que queremos, en este caso 2.

In [32]:
v1[2] = 10000

In [33]:
v1[2]

10000.0

In [29]:
v2 = array([5.5, 9, 3, 4])

In [30]:
v2

array([5.5, 9. , 3. , 4. ])

In [69]:
v1 + v2 

array([ 6.5, 11.5, 12. , 13. ])

In [70]:
M = array([[1, 2], [3, 4]])

In [72]:
I = array([[1, 0], [0, 1]])

In [73]:
M*I

array([[1, 0],
       [0, 4]])

### Reshape

In [74]:
dot(M, I)

array([[1, 2],
       [3, 4]])

In [75]:
x = arange(27)

In [76]:
x

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19, 20, 21, 22, 23, 24, 25, 26])

In [77]:
w = arange(10, 20)

In [78]:
w

array([10, 11, 12, 13, 14, 15, 16, 17, 18, 19])

In [79]:
type(w)

numpy.ndarray

In [85]:
y = arange(18).reshape(2, 3, 3)

In [86]:
y

array([[[ 0,  1,  2],
        [ 3,  4,  5],
        [ 6,  7,  8]],

       [[ 9, 10, 11],
        [12, 13, 14],
        [15, 16, 17]]])